config/routes.rb
Rails.application.routes.draw do
  resources :farms_maps
  resources :events
  devise_for :users
  resources :resource_attachments
  resources :resources
  get 'pages/index'
  get 'calendar' => 'pages#calendar'
  get 'plantdb' => 'pages#resources'
  get 'map' => 'pages#map_florida'
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resource_attachment.rb
class ResourceAttachment < ApplicationRecord
  mount_uploader :picture, PictureUploader
   belongs_to :resource
end

app/controllers/resource_attachments_controller.rb
class ResourceAttachmentsController < ApplicationController
  before_action :set_resource_attachment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /resource_attachments
  # GET /resource_attachments.json
  def index
    @resource_attachments = ResourceAttachment.all
  end

  # GET /resource_attachments/1
  # GET /resource_attachments/1.json
  def show
    @plants = Resource.all
  end

  # GET /resource_attachments/new
  def new
    @resource_attachment = ResourceAttachment.new
  end

  # GET /resource_attachments/1/edit
  def edit
  end

  # POST /resource_attachments
  # POST /resource_attachments.json
  def create
    @resource_attachment = ResourceAttachment.new(resource_attachment_params)

    respond_to do |format|
      if @resource_attachment.save
        format.html { redirect_to @resource_attachment, notice: 'Resource attachment was successfully created.' }
        format.json { render :show, status: :created, location: @resource_attachment }
      else
        format.html { render :new }
        format.json { render json: @resource_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_attachments/1
  # PATCH/PUT /resource_attachments/1.json
  def update
    respond_to do |format|
    if @resource_attachment.update(resource_attachment_params)
      format.html { redirect_to edit_resource_path(@resource_attachment.resource_id), notice: 'Post attachment was successfully updated.' }
    end
  end
  end

  # DELETE /resource_attachments/1
  # DELETE /resource_attachments/1.json
  def destroy
    @resource_attachment.destroy
    Dir.delete("public/uploads/resource_attachment/picture/#{@resource_attachment.id}")
    respond_to do |format|
      # IDEALredirect => edit_resource_path(@resource_attachment.resource_id)
      format.html { redirect_to edit_resource_path(@resource_attachment.resource_id), notice: 'Resource attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_attachment
      @resource_attachment = ResourceAttachment.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_attachment_params
      params.require(:resource_attachment).permit(:resource_id, :picture, :caption, :rotate)
    end
end

app/helpers/resource_attachments_helper.rb
module ResourceAttachmentsHelper
end

app/views/resource_attachments/_form.html.erb
<div class="container resourceBG">
  <div class="plantPictures">
    <%= image_tag @resource_attachment.picture, class: 'showPics' %>
    <%= form_for(@resource_attachment) do |f| %>
      <div class="field" style="color:yellow;">
        <%= f.text_field :caption, placeholder: "Add a caption!", class: 'textField' %>
      </div>
      <br>
      Rotated
      <span style="color:black">
        <%= f.select(:rotate, [0, 90, 180, 270]) %>
      </span> degrees
      <br>
      <div class="field changePic">
        <strong>Change Picture</strong><br>
        <small>Warning: do not do anything here unless you wish to change the picture!</small>
        <br><br>
        <%= f.file_field :picture, class: 'filin' %>
        <br><br>
      </div>

      <div class="actions" align="center">
        <%= f.submit "Update Picture", class: "btn btn-warning btn-lg" %>
      </div>
      <br>
  </div>
  <% end %>
</div>

app/views/resource_attachments/edit.html.erb
<br>
<div class="container">
<h1>Editing Resource Attachment</h1>
<%= link_to 'Back', resource_path(@resource_attachment.resource_id), class: "btn btn-warning" %>

<%= render 'form', resource_attachment: @resource_attachment %>


</div>

app/views/resource_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resource Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Resource</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resource_attachments.each do |resource_attachment| %>
      <tr>
        <td><%= resource_attachment.resource_id %></td>
        <td><%= resource_attachment.picture %></td>
        <td><%= link_to 'Show', resource_attachment %></td>
        <td><%= link_to 'Edit', edit_resource_attachment_path(resource_attachment) %></td>
        <td><%= link_to 'Destroy', resource_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource Attachment', new_resource_attachment_path %>

app/views/resource_attachments/new.html.erb
<h1>New Resource Attachment</h1>

<%= render 'form', resource_attachment: @resource_attachment %>

<%= link_to 'Back', resource_attachments_path %>

app/views/resource_attachments/show.html.erb
<br>
<div class="container">
<p>
  <strong>Resource:</strong>
  <%= @plants.find(@resource_attachment.resource_id).common %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @resource_attachment.picture_url %>
</p>

<%= link_to 'Edit', edit_resource_attachment_path(@resource_attachment) %> |
<%= link_to 'Back', resource_path(@resource_attachment.resource_id) %>
</div>