config/routes.rb
Rails.application.routes.draw do
  resources :farms_maps
  resources :events
  devise_for :users
  resources :resource_attachments
  resources :resources
  get 'pages/index'
  get 'calendar' => 'pages#calendar'
  get 'plantdb' => 'pages#resources'
  get 'map' => 'pages#map_florida'
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/farms_map.rb
class FarmsMap < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  validates :name, :address, presence: true
end

app/controllers/farms_maps_controller.rb
class FarmsMapsController < ApplicationController
  before_action :set_farms_map, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /farms_maps
  # GET /farms_maps.json
  def index
    @farms_maps = FarmsMap.all.paginate(:page => params[:page], :per_page => 25)
  end

  # GET /farms_maps/1
  # GET /farms_maps/1.json
  def show
  end

  # GET /farms_maps/new
  def new
    @farms_map = FarmsMap.new
  end

  # GET /farms_maps/1/edit
  def edit
  end

  # POST /farms_maps
  # POST /farms_maps.json
  def create
    @farms_map = FarmsMap.new(farms_map_params)

    respond_to do |format|
      if @farms_map.save
        format.html { redirect_to farms_maps_path, notice: '#{@farms_map.name} was successfully added to the map!' }
        format.json { render :show, status: :created, location: @farms_map }
      else
        format.html { render :new }
        format.json { render json: @farms_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms_maps/1
  # PATCH/PUT /farms_maps/1.json
  def update
    respond_to do |format|
      if @farms_map.update(farms_map_params)
        format.html { redirect_to farms_maps_path, notice: "#{@farms_map.name} was successfully updated!" }
        format.json { render :show, status: :ok, location: @farms_map }
      else
        format.html { render :edit }
        format.json { render json: @farms_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms_maps/1
  # DELETE /farms_maps/1.json
  def destroy
    @farms_map.destroy
    respond_to do |format|
      format.html { redirect_to farms_maps_url, notice: 'Farms map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farms_map
      @farms_map = FarmsMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farms_map_params
      params.require(:farms_map).permit(:name, :address, :latitude, :longitude, :description)
    end
end

app/helpers/farms_maps_helper.rb
module FarmsMapsHelper
end

app/views/farms_maps/_form.html.erb
<%= form_for(farms_map) do |f| %>
  <% if farms_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farms_map.errors.count, "error") %> prohibited this farms_map from being saved:</h2>

      <ul>
      <% farms_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Name of Location", class: "textField mapsField" %>
  </div>

  <div class="field">
    <%= f.text_field :address, placeholder: "Direct Address of Location", class: "textField mapsField2" %>
  </div>

  <div class="field hidden">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field hidden">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <br><br>
  <div class="field" style="background-color:white;">
    <div style="font-size: 22px;margin-bottom:20px;"><strong>Description</strong><hr></div>
    <%= f.trix_editor :description %>
  </div>

  <br>
  <div class="actions" align="center">
    <%= f.submit "Save to Map", class: "btn btn-warning btn-lg" %>
  </div>
<% end %>
<div style="height:150px;"></div>

app/views/farms_maps/edit.html.erb
<div class="container">
  <br>
<h1>Editing: <%= @farms_map.name %></h1>
<%= link_to 'Back', farms_maps_path, class: "btn btn-warning" %>

<%= render 'form', farms_map: @farms_map %>

</div>

app/views/farms_maps/index.html.erb
<div class="container">
<br>
<h1>Index of Locations for Farm Map</h1>
<%= link_to 'View Map', map_path, class: "btn btn-primary", data: {turbolinks: false} %>
<%= link_to 'Add a New Location', new_farms_map_path, class: "btn btn-warning" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th style="width:654px;">Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @farms_maps.reverse.each do |farms_map| %>
      <tr>
        <td><%= farms_map.name %></td>
        <td><%= farms_map.address %></td>
        <td>
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapsed_<%= farms_map.id %>" aria-expanded="false" aria-controls="collapsed_<%= farms_map.id %>">
          Show Description as it is currently
        </button>
        <div class="collapse" id="collapsed_<%= farms_map.id %>">
          <div class="well">
            <div class="farmName">
              <%= farms_map.name %>
            </div>
            <%= farms_map.description.html_safe %>
          </div>
        </div>
        </td>
        <td><%= link_to 'Edit', edit_farms_map_path(farms_map), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', farms_map, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to remove this from the map?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @farms_maps, class: 'digg_pagination' %>
</div>

app/views/farms_maps/new.html.erb
<div class="container">
  <br>
<h1>New Location for Map</h1>
<%= link_to 'Back', farms_maps_path, class: "btn btn-warning" %>

<%= render 'form', farms_map: @farms_map %>

</div>

app/views/farms_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @farms_map.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @farms_map.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @farms_map.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @farms_map.longitude %>
</p>

<p>
  <strong>Description:</strong>
  <%= @farms_map.description.html_safe %>
</p>


<%= link_to 'Edit', edit_farms_map_path(@farms_map) %> |
<%= link_to 'Back', farms_maps_path %>