config/routes.rb
Rails.application.routes.draw do
  resources :farms_maps
  resources :events
  devise_for :users
  resources :resource_attachments
  resources :resources
  get 'pages/index'
  get 'calendar' => 'pages#calendar'
  get 'plantdb' => 'pages#resources'
  get 'map' => 'pages#map_florida'
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_filterEvents.html.erb
<div class="searchBar">
  <h3>Event Calendar</h3>
  <%= form_tag calendar_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search], :style => "color:black;" %>
      <%= button_tag(type: "submit", :name => nil, class: "btn btn-sm btn-danger") do %>
        <i class="fa fa-search"></i>
      <% end %>
      <%= link_to "All", calendar_path, class: "btn btn-sm btn-warning" %>
    </p>
  <% end %>
</div>

app/views/pages/_filterNav.html.erb
<div class="searchBar">
  <h3>Plant Database</h3>
  <%= link_to "Home", root_path, class: "btn btn-danger"%><%= link_to "All", plantdb_path, class: "btn btn-warning" %>
  <%= form_tag plantdb_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search], :style => "color:black;" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-danger" %>
    </p>
  <% end %>
</div>
  <!-- <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Genus <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% @resources.each do |genus| %>
        <li><a href="#<%= genus.binomial.gsub(" ", '')%>"><%= genus.binomial.split(" ")[0] %></a></li>
      <% end %>
    </ul>
  </div> -->

app/views/pages/_filterPlants.html.erb
<div class="searchBar">
  <h3>Plant Database</h3>
  <%= form_tag plantdb_path, :method => 'get' do %>
    <p class="formArea">
      <%= text_field_tag :search, params[:search], :style => "color:black;" %>
      <%= button_tag(type: "submit", :name => nil, class: "btn btn-sm btn-danger") do %>
        <i class="fa fa-search"></i>
      <% end %>
      <%= link_to "All", plantdb_path, class: "btn btn-sm btn-warning" %>
      <%#= submit_tag "Search", :name => nil, class: "btn btn-danger" %>
    </p>
  <% end %>
</div>

app/views/pages/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                Menu <i class="fa fa-bars"></i>
            </button>
            <div class="navbar-brand">
                  <i class="glyphicon glyphicon-leaf"></i> <span class="light">Bamboo</span> Grove
            </div>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "PlantDB", plantdb_path %></li>
                <li>
                    <!-- <a class="page-scroll" href="#calendar">Calendar</a> -->
                    <%= link_to "Calendar", calendar_path %>
                </li>
                <li><%= link_to("Farms Map", map_path, data: { turbolinks: false })%></li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
                <% if current_user %>
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Admin <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li style="background:#1d9b6c;"><%= link_to "Plant Index", resources_path %></li>
                    <li style="background:#1d9b6c;"><%= link_to "Event Index", events_path %></li>
                    <li style="background:#1d9b6c;"><%= link_to "Map Index", farms_maps_path %></li>
                    <li style="background:#d9534f;"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>


                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div style="position:absolute;width:70%;margin-left:15%;background:transparent;top:55px;" align="center">
<% unless flash[:notice].nil? %>
  <div class="alert alert-warning alert-dismissible animated fadeInDown">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:notice] %></div>
<%end%>
</div>

app/views/pages/calendar.html.erb
<br>

<div class="container">
  <div align="right">
    <% if current_user %>
      <%= link_to "Add New Event", new_event_path, class: "btn btn-warning" %>
    <% end %>
  </div>

<%= render 'pages/filterEvents' %>
<% if @events.count == 0 %>
  <strong> Your search came up with nothing!</strong>
  <br>
  Try:
  <ul>
    <li>Searching by location of event</li>
    <li>Searching by what might be in the description</li>
    <li>Spelling all or part of the above correctly</li>
  </ul>
<% else %>
<div class="row">
  <% @events.each do |event| %>

  <div class="col-md-4">
    <div class="panel panel-default" style="background:transparent;height:200px;border:none;box-shadow:none;">
      <div class="panel-body" style="text-align:center;overflow:hidden;">

        <div class="calIndex">
          <%= link_to event, data: { turbolinks: false } do %>
            <h3><%= event.name %></h3><br>
            <h4><%= event.location %></h4>
          <% end %>
        </div>

        <% if Time.now > event.end_time %>
          <% ending = " ago" %>
        <% elsif Time.now < event.start_time %>
          <% ending = " from now" %>
        <% end %>

        <% btn_disp = event.start_time.strftime('%b %d, %Y').to_s + " >> [" + distance_of_time_in_words(Time.now, event.start_time).sub("about", '') + ending + "]"  %>
        <%= link_to btn_disp, event, data: { turbolinks: false }, class: "btn btn-danger", :style => 'width:100%;box-shadow:2px 2px 5px rgba(0,0,0,0.3);' %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>
<div style="text-align:center">
  <%= will_paginate @events, class: 'digg_pagination' %>
</div>
</div>
</div>

app/views/pages/index.html.erb
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2" style="background:rgba(0,0,0,0.4);border-radius:25px;">
                        <h1 class="brand-heading">Bamboo Grove</h1>
                        <p class="intro-text">Aligning Florida with the vast world of plants and plant related events
                          <br>
                    </div>
                </div>
                <a href="#about" class="btn btn-circle page-scroll">
                    <i class="fa fa-angle-double-down animated"></i>
                </a>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Bamboo Grove</h2>
                <p>Bamboo Grove is based in Arcadia, FL where Andy Firk tends the land to better serve the community at large. It features a 2 acre food forest and a diverse plant nursery and seed stock, ready to get you growing in Florida! In addition to the plants of the land, Andy Firk leads wild edible plant walks, presents indepth lectures on wild, edible, and medicinal plants, and organizes a ton of information!</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="calendar" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">

                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Start Bootstrap</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2016</p>
            <p>Thanks to <%= link_to "Andy Firk", new_user_session_path, :style => "color:white;" %>!</p>
        </div>
    </footer>

app/views/pages/map_florida.html.erb
<div>
<% if current_user %>
<br>
  <%= link_to "Manage Locations", farms_maps_path, class: "btn btn-danger" %>
<% end %>
</div>
<div id="mapCanvas"></div>


<script src="https://maps.googleapis.com/maps/api/js?key=#{ENV['Farms_maps_api']}"></script>


<script>

function initMap() {
    var map;
    var bounds = new google.maps.LatLngBounds();
    var mapOptions = {
        mapTypeId: 'roadmap'
    };

    // Display a map on the web page
    map = new google.maps.Map(document.getElementById("mapCanvas"), mapOptions);
    map.setTilt(50);

    // Multiple markers location, latitude, and longitude
    var markers = <%= raw(@locations) %>;

    // Info window content
    var infoWindowContent = <%= raw(@descriptions) %>;

    // Add multiple markers to map
    var infoWindow = new google.maps.InfoWindow(), marker, i;

    // Place each marker on the map
    for( i = 0; i < markers.length; i++ ) {
        var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: map,
            title: markers[i][0]
        });

        // Add info window to marker
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infoWindow.setContent(infoWindowContent[i][0]);
                infoWindow.open(map, marker);

            }
        })(marker, i));

        // Center the map to fit all markers on the screen
        map.fitBounds(bounds);
    }

    // Set zoom level
    var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
        this.setZoom(7);
        google.maps.event.removeListener(boundsListener);
    });

}


// Load initialize function
google.maps.event.addDomListener(window, 'load', initMap);


</script>

app/views/pages/resources.html.erb
<br>
<div class="container">
<div align="right">
  <% if current_user %>
    <%= link_to "Add New Plant", new_resource_path, class: "btn btn-warning" %>
  <% end %>
</div>
<%= render 'pages/filterPlants' %>

<% if @resources.count == 0 %>
  <strong> Your search came up with nothing!</strong>
  <br>
  Try:
  <ul>
    <li>Searching by genus</li>
    <li>Searching by species</li>
    <li>Spelling all or part of the common name correctly</li>
    <li>'edible'</li>
    <li>'tea'</li>
    <li>'tuber'</li>
  </ul>
<% else %>
  <div class="row">
    <% @resources.each do |plant| %>
    <div class="col-md-4">
      <div class="panel panel-default" style="background:transparent;border:none;height:250px;box-shadow:none;">
        <div class="panel-body" style="text-align:center;overflow:hidden;">
          <%= link_to plant do %>
            <% if plant.resource_attachments[0] == nil %>
              <%= image_tag image_path("no-image.jpg"), class: 'showPics' %>
            <% else %>
              <%= image_tag plant.resource_attachments[0].picture_url, class: 'showPics' %>
            <% end %>
          <% end %>

          <%= link_to plant.binomial, plant, class: "btn btn-danger", :style => 'width:100%;box-shadow:2px 2px 5px rgba(0,0,0,0.3);' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
<div style="text-align:center">
  <%= will_paginate @resources, class: 'digg_pagination' %>
</div>
</div>