config/routes.rb
Rails.application.routes.draw do
  resources :farms_maps
  resources :events
  devise_for :users
  resources :resource_attachments
  resources :resources
  get 'pages/index'
  get 'calendar' => 'pages#calendar'
  get 'plantdb' => 'pages#resources'
  get 'map' => 'pages#map_florida'
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<%= form_for(@resource, :html => { :multipart => true }) do |f| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container resourceBG">

<div class="plantName">
  <div class="form-group">
    <%= f.text_field :common, placeholder: "Common Name(s)", class: 'plantCName textField' %>
  </div>

  <div class="form-group">
    <%= f.text_field :binomial, placeholder: "Binomial name", class: 'plantLName textField' %>
  </div>
</div>

<div class="plantDesc">
  <div class="form-group" style="max-width:100%;">
    <%= f.label :description %>
    <%= f.trix_editor :description %>
  </div>
  <span style="color:red;">>>> Save any text before adding additional photos or editing captions!</span>
</div>


<% unless @resource_attachments.nil? %>
  <% @resource_attachments.each do |p| %>
    <div class="plantPictures">
      <div class="<%= rotateImage(p.rotate) %>">
        <%= link_to p.picture_url do %>
          <%= image_tag p.picture_url %>
        <%end%>
      </div>
    </div>
     <div class="picCaption">
      <%= p.caption %><br>
      <%= link_to "Edit Caption / Change Picture", edit_resource_attachment_path(p), class: "btn btn-warning" %>
      <%= link_to "Remove Picture", resource_attachment_path(p), method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
  <% end %>
  <br>
  <br><br>
<div class="picCaption">
  <strong>Add a Picture:</strong>
  <%= f.file_field :picture, :multiple => true, name: "resource_attachments[picture][]", class: 'filin' %>
  <br>
</div>



  <br>

  <div class="actions" align="center">
    <%= f.submit "Update", class: "btn btn-warning btn-lg" %>
  </div>


<% end %>
</div>

app/views/resources/edit.html.erb
<div class="container">
  <br>
<h1>Editing Plant File</h1>
<%= link_to 'Back', resource_path(@resource.id), class: "btn btn-warning" %>

<%= render 'form', resource: @resource %>

app/views/resources/index.html.erb
<br>
<div class="container">
<h1>Index of Plant Files</h1>
<%= link_to 'View All', plantdb_path, class: "btn btn-primary" %>
<%= link_to 'Add a New Plant', new_resource_path, class: "btn btn-warning" %>

<table class="table">
  <thead>
    <tr>
      <th>Binomial</th>
      <th>Common</th>
      <th style="width:654px;">Description</th>
      <th>Pictures</th>
      <th colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.reverse.each do |resource| %>
      <tr>
        <td><%= resource.binomial %></td>
        <td><%= resource.common %></td>
        <td>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapsed_<%= resource.id %>" aria-expanded="false" aria-controls="collapsed_<%= resource.id %>">
            Show Description as it is currently
          </button>
          <div class="collapse" id="collapsed_<%= resource.id %>">
            <div class="well" style="background:transparent; border:none;">
              <div class="plantDesc" style="font-size: 1em;">
                <%= resource.description.html_safe %>
              </div>
            </div>
          </div>
        </td>
        <td>

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#<%= resource.id %>pics">
            <%= resource.resource_attachments.count %>
          </button>

          <div class="modal fade" id="<%= resource.id %>pics" tabindex="-1" role="dialog" aria-labelledby="<%=resource.id %>picsLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" style="color:black">Pics for <%= resource.common %></h4>
                </div>
                <div class="modal-body">
                  <% resource.resource_attachments.each do |pic| %>
                    <%= image_tag pic.picture_url, :style => 'width:100%;' %>
                    <br><br>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->
        </td>
        <td><%= link_to 'Show', resource, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @resources, class: 'digg_pagination' %>
</div>

app/views/resources/new.html.erb
<div class="container">
  <br>
<h1>New Plant File</h1>
<%= link_to 'Back', plantdb_path, class: "btn btn-warning" %>


<%= render 'form', resource: @resource %>

app/views/resources/show.html.erb
<br>
<div class="container">

<%= link_to 'Back', plantdb_path, class: "btn btn-primary" %>
<% if current_user %>
  <%= link_to 'Edit', edit_resource_path(@resource), class: "btn btn-warning" %>
  <%= link_to 'Remove Plant File', resource_path(@resource.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to remove this plant file?"} %>
<% end %>
</div>
<div class="container resourceBG">

<div class="plantName">
  <div class="plantCName">
    <%= @resource.common %>
  </div>
  <div class="plantLName">
    <%= @resource.binomial %>
  </div>
</div>

<!-- <h3 class="labelBox">Description</h3> -->

<div class="plantDesc">
  <%= @resource.description.html_safe %>
</div>

<!-- <h3 class="labelBox">Pictures</h3> -->
  <% @resource_attachments.each do |p| %>
  <div class="plantPictures">
    <div class="<%= rotateImage(p.rotate) %>">
      <%= link_to p.picture_url do %>
        <%= image_tag p.picture_url %>
      <%end%>
    </div>
     <br>
  </div>
  <div class="picCaption">
    <%= p.caption %><br>
  </div>
  <% end %>



</div>